### ISSUE TITLE
LOMAP generates two different perturbation networks for the same setr of ligands

### ISSUE THREAD

**Issue by jasmin-guven** [meyresearch/metalloenzymes#1]
LOMAP generates two very different perturbation networks for the same set of ligands obtained from [Pemberton et.al.](https://doi.org/10.1021/acs.jmedchem.9b00728) when docked to KPC-2 and to VIM-2 separately. The only difference in the two groups (apart from docking) is that for KPC-2 we use a crystal structure for ligand 1 and for VIM-2 we use a crystal structure for ligand 8. The problem may be caused (at least partly) by the different ordering of atoms in these files compared to the non-crystal structure files. 

LOMAP also seems to add an additional hydrogen atom to the representation of the phosphonate group. A double-bonded oxygen is missing in this representation, and one of the other oxygens should also be bonded to hydrogen. 

Attached docked ligand files, csv files containing perturbations and their scores.

BioSimSpace version: 2022.2.1+275.g8b2b6a0f
Lomap version: 2.1.0

[kpc2_docked.zip](https://github.com/meyresearch/metalloenzymes/files/10005889/kpc2_docked.zip)
[vim2_docked.zip](https://github.com/meyresearch/metalloenzymes/files/10005890/vim2_docked.zip)
[lomap_kpc2.csv](https://github.com/meyresearch/metalloenzymes/files/10005895/lomap_kpc2.csv)
[lomap_vim_2.csv](https://github.com/meyresearch/metalloenzymes/files/10005896/lomap_vim_2.csv)

### VIM-2
![vim_2_network](https://user-images.githubusercontent.com/57833295/201734997-e11ec70d-8cc1-4d26-bac1-ac9e9114632a.png)

### KPC-2
![kpc_2_network](https://user-images.githubusercontent.com/57833295/201735082-93c9b111-a9c8-4fcf-8bd4-65215ffec5d3.png)

**Comment by RiesBen** [comment]
Hi @jasmin-guven,
I had a quick look at your sdf file, the rdkit representation is 'correct' regarding to what is inside the sdf files.

In the bond blocks of the sdfs you can see, that there are only single bonds noted for the phosphonate .
Here the bond block for phosphor to the other atoms (at least for two rows there should be a 2 in the third column to assing double bonds.)

_in docked_1.sdf line 47-50_:

` 15  7  1  0`
` 15 12  1  0`
` 15 13  1  0`
` 15 14  1  0`

Correcting this will remove the hydrogen added by rdkit to make somehow a reasonable structure ;)

**Comment by RiesBen** [comment]
regarding the mappings, why do you want them to be equal? To my knowledge Lomap includes the 3D information to get the best mappings and network for the ligands. As the free energy is a state function (path independent) there should not be a problem from a thermodynamic point of view. :)
